ADDON_NAME = 'Color Prime'
ADDON_ID = 'color_prime'
VERSION = (3, 5, 2)
VERSION_STRING = '.'.join((str(v) for v in VERSION))
SCHEMA_VERSION = 10
FAMILY_ITEMS = (('MAIN', 'Main', 'Inherit from the Main family color'), ('ACCENT', 'Accent', 'Inherit from the Accent family color'), ('FIXED', 'Fixed', 'Never recolor this material'), ('IGNORE', 'Ignore', 'Do not manage this material'))
INHERITANCE_ITEMS = (('OKLCH', 'Perceptual', 'Preserve shade/chroma/hue relationship in OKLCH'), ('DIRECT', 'Direct', 'Use the family color exactly'), ('RGB_GAIN', 'RGB Gain', 'Preserve the original per-channel ratio'))
ROOT_KIND_ITEMS = (('OBJECT', 'Object Root', 'An object and all descendants'), ('COLLECTION', 'Collection Root', 'A collection and nested collections'))
TARGET_KIND_ITEMS = (('PATH_RGB', 'Color Dependency', 'Nested authored RGB source'), ('PATH_INPUT', 'Color Dependency Input', 'Nested instance-local input'), ('NONE', 'Unresolved', 'No safe writable target'), ('NODE_INPUT', 'Node Input', 'A local unlinked node input'), ('RGB_OUTPUT', 'RGB Node', 'A local RGB node output'), ('LEGACY_GROUP_RGB', 'Localized Legacy Group', 'RGB inside a material-local group copy'))
COMBINATION_ITEMS = (('MATRIX', 'All combinations', 'Render every enabled Main × Accent combination'), ('PAIRED', 'Pair by index', 'Pair by index; broadcast a one-item palette'))
RESOLUTION_MODE_ITEMS = (('SCALE', 'Scale', "Scale the scene's base render size"), ('ABSOLUTE', 'Absolute', 'Use an explicit width and height'))
TRANSPARENCY_ITEMS = (('KEEP', 'Use Scene', 'Keep current Film > Transparent'), ('ON', 'Transparent', 'Force transparent film'), ('OFF', 'Opaque', 'Force opaque film'))
ERROR_POLICY_ITEMS = (('STOP', 'Stop on error', 'Stop and restore immediately'), ('SKIP', 'Skip failed task', 'Log the error and continue'))
DETECTION_MODE_ITEMS = (('SAFE', 'Safe', 'Tagged roots, Anchor_ roots and clear icon collections'), ('TAGGED', 'Tagged only', 'Only roots marked for Color Prime'), ('LEGACY', 'Legacy Anchor_', 'Only objects beginning with Anchor_'), ('SMART', 'Smart scene scan', 'Also inspect top-level empties and collections'))
DIAGNOSTIC_LEVEL_ITEMS = (('INFO', 'Info', 'Informational'), ('WARNING', 'Warning', 'Needs review'), ('ERROR', 'Error', 'Blocks reliable rendering'))
GEOMETRY_ANALYSIS_ITEMS = (('AUTO', 'Camera then Surface', 'Use active-camera projected coverage; fall back to world-space triangle area'), ('CAMERA', 'Projected Area', 'Projected triangle area; overlaps and occlusion are NOT resolved'), ('WORLD', 'Surface Area', 'Use transformed world-space triangle area only'))
LOOSE_PART_MODE_ITEMS = (('OFF', 'Off', 'Never assign materials by disconnected mesh islands'), ('TWO_ONLY', 'Exactly Two Islands', 'If a one-material mesh has exactly two disconnected islands, assign larger Main and smaller Accent'), ('ALL', 'All Islands', 'Group disconnected islands into dominant Main and detail Accent sets'))
REFERENCE_BACKGROUND_ITEMS = (('AUTO', 'Auto Border/Alpha', 'Ignore transparent pixels and a likely border background color (heuristic, not a foreground mask)'), ('KEEP', 'Keep All Colors', 'Do not remove an opaque border background'), ('FORCE_BORDER', 'Force Border Background', 'Treat the strongest border color as background even at lower confidence'))
COLOR_SOCKET_ALIASES = ('CP Color', 'Color Prime', 'Base Color', 'Color', 'Tint', 'Albedo')
EXPLICIT_TARGET_TOKENS = ('cp_color', 'color_prime', 'colorprime', 'family_color')
MAIN_NAME_TOKENS = ('main', 'base', 'primary', 'body', 'shell', 'basecolor', 'base_color')
ACCENT_NAME_TOKENS = ('accent', 'secondary', 'detail', 'trim', 'ornament', 'accentcolor', 'accent_color')
DEFAULT_PROTECTED_KEYWORDS = ()
DEFAULT_FIXED_NAME_SUFFIX = '!'
ICON_COLLECTION_TOKENS = ('icon', 'icons', 'colorprime', 'color_prime')
LEGACY_MAIN_PREFIXES = ('BaseColor', 'MainColor', 'PrimaryColor')
LEGACY_ACCENT_PREFIXES = ('AccentColor', 'SecondaryColor')
MANIFEST_FILENAME = 'color_prime_manifest.jsonl'
LOG_TEXT_NAME = 'Color Prime Log'
